# Generated by Django 4.0.5 on 2022-06-08 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='discount',
        ),
    ]
