# Generated by Django 4.0.5 on 2022-06-08 14:34

import app.models.coupon
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_products_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('discount', models.IntegerField()),
                ('code', models.CharField(default=app.models.coupon.random_code, max_length=6, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='app.products')),
            ],
        ),
    ]
